version: '2.1'

services:
  tuchosa-node:
  tuchosa-backend:
    build: .
    ports:
      - 3000:3000
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    depends_on:
      - db
    env_file:
     - ./.env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_DB}:5432/${MASTER_SCHEMA}
      - TEST_DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${TEST_POSTGRES_DB}:5432/${MASTER_SCHEMA}
      - PORT=${PORT}
    volumes:
      - .:/opt/app
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
    command: node --inspect server.js
  db:
    image: postgres
    env_file:
     - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}